### PR TITLE
Fixed several typos in MainActivity.java file

### PR DESCRIPTION
**Pull request by thedevelopersanjeev**

### CODE REVIEW

**Comment by kkdroidgit** [comment]
Make changes in `row_layout.xml` also and send another PR :+1:

**Comment by kkdroidgit** [comment]
Check your row_layout.xml again. Another text view is redundant

**Comment by thedevelopersanjeev** [comment]
fixed! that was just a typing error

**Comment by kkdroidgit** [comment]
Congratulations @thedevelopersanjeev! Nice buddy more to come!

**Pull request closed without merging**
