### PR TITLE
First commit

### PR DESCRIPTION
**Pull request by athulaugustine**
Changed Mainactivity java file

### CODE REVIEW

**Comment by kkdroidgit** [comment]
Hi @athulaugustine. The changes made in `MainActivity.java` are absolutely correct. Though looks like you missed the changes in `row_layout.xml`. Send another PR with the changes. :)

**Comment by athulaugustine** [comment]
Final

**Comment by athulaugustine** [comment]
Cant submit another pull request

**Comment by kkdroidgit** [comment]
@athulaugustine Good Job

**Pull request closed without merging**
